import * as fs from "node:fs/promises";
import * as path from "node:path";
import type { ScanReport } from "./scanner.js";

const HEADER = "# Generated by ProdShield Pre-Flight Fixer";

function parseKeys(content: string): Set<string> {
  const keys = new Set<string>();
  for (const line of content.split(/\r?\n/)) {
    const match = line.trim().match(/^(?:export\s+)?([A-Za-z0-9_]+)\s*=/);
    if (match && match[1]) keys.add(match[1]);
  }
  return keys;
}

export async function runFixer(report: ScanReport, targetDir: string): Promise<string[]> {
  const actions: string[] = [];
  const examplePath = path.join(path.resolve(targetDir), ".env.example");

  if (report.missingEnv.length > 0) {
    let existing: string | null = null;
    try {
      existing = await fs.readFile(examplePath, "utf8");
    } catch {
      existing = null;
    }

    const declared = existing === null ? new Set<string>() : parseKeys(existing);
    const toAdd = [...new Set(report.missingEnv.map((e) => e.variable))].filter(
      (v) => !declared.has(v)
    );
    const lines = toAdd.map((v) => `${v}=your_${v.toLowerCase()}_here`);

    if (existing === null) {
      await fs.writeFile(examplePath, [HEADER, ...lines].join("\n") + "\n", "utf8");
      actions.push(`Created .env.example with ${lines.length} variables`);
    } else if (lines.length > 0) {
      const separator = existing.length === 0 || existing.endsWith("\n") ? "" : "\n";
      await fs.appendFile(examplePath, separator + lines.join("\n") + "\n", "utf8");
      actions.push(`Appended ${lines.length} missing variables to .env.example`);
    }
  }

  return actions;
}
